#!/bin/sh
# Initializes the RaspiCopter completely

# Prepare our UART
stty -F /dev/ttyAMA0 115200 raw

# Init our low-level control
modprobe i2c-dev
./msp reset
sleep 0.5s
./initIMU # this will put the MPU6050 into 6-DOF DMP mode
./msp initdmp # this initializes the MPU


