#!/bin/sh
# Sends a simple command to the MSP430  controller
if [ -z "$1" ]; then echo "$0 00 11 22 33" >&2; exit 1; fi
STR=
for i in $@ FF; do STR=${STR}$(echo -en "\x$i") ; done
echo -n "${STR}" > /dev/ttyAMA0
