#!/bin/sh
# Sends a simple command to the MSP430  controller
if [ -z "$1" ]; then 
  echo "$0 set 0x00 [...] " >&2; 
  echo "$0 setpid kP kI kD iMin iMax oMin oMax" >&2; 
  exit 1;
 fi

CMD="$1"
shift

# Parse command
case "$CMD" in
  "set")
    DATA="$@"
    for i in $(seq $# 4); do DATA="$DATA 00"; done
    ;;
esac

# Execute
echo "$DATA 0xFF" | xxd -r > /dev/ttyAMA0
